const REVIEW_REWARD_POINTS = 2000;
const REVIEW_WINDOW_DAYS = 90;
const SIGNUP_COUPON_CODE = "WELCOME10000";
const SIGNUP_COUPON_AMOUNT = 10000;

module.exports = {
  REVIEW_REWARD_POINTS,
  REVIEW_WINDOW_DAYS,
  SIGNUP_COUPON_CODE,
  SIGNUP_COUPON_AMOUNT,
};
